name: "Terraform Apply"

on:
  push:
    branches:
      - master
    paths:
      - 'terraform/**'

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment:
      name: Production  
      url: https://portal.azure.com

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: cd terraform/Practice && terraform init -input=false

      - name: Terraform Apply
        run: cd terraform/Practice && terraform apply -auto-approve
